os:
  - linux

language: php

php:
  - '7.1'
  
before_script:
  - cd application/src
  - composer self-update
  - composer install --no-interaction
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  
script:
  - vendor/bin/phpunit --coverage-text
 