version: '3'
services:
  application:
    image: ossaijad/lumen-tdd:latest
    networks:
     - appnet
  application-gateway:
    image: ossaijad/lumen-tdd-gateway:latest
    ports:
     - "80:80"
    networks:
     - appnet
    depends_on:
      - server
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
  networks:
    appnet:
      driver: "bridge"
  volumes:
  data:
    driver: "local"
